{% set name = "quantiphyse-fabber" %}
{% set version = "0.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quantiphyse-fabber-{{ version }}.tar.gz
  sha256: bb6db8afefc3be34ac4826955af0b1bc7ad1506c782d96e62acc0d3d89f162fd

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - pyfab
    - python >={{ python_min }}
    - quantiphyse

test:
  requires:
    - python {{ python_min }}
  imports:
    - PySide2
    - quantiphyse_fabber

about:
  home: https://quantiphyse.readthedocs.io/
  summary: Quantiphyse plugin for Fabber Bayesian modelling tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcraig-ibme
